### ISSUE TITLE
Windows: Debug: Errlog tried to debug the error but the stack trace seems empty

### ISSUE THREAD

**Issue by jan-herout** [snwfdhmp/errlog#11]
Hi there, kudos for what seems to be an interesting library! Since I am learning Go, I really want to try it out.

On Windows `.errlog/examples/basic/basic.go` fails. The error I get is in subject.

Cursory glance at the code reveals problem with `parsedRes := regexpParseStack.FindAllStringSubmatch(stack, -1)`, where length of `parsedRes` is zero.

The regexp is too ugly to understand at the first glance (and I have Perl background :) ), so I stopped my analysis there.

Example stack trace (partial):

```
goroutine 6 [running]:
runtime/debug.Stack(0x18, 0x30, 0x30)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/snwfdhmp/errlog.parseStackTrace(0x2, 0x700200, 0xc00001e4c0, 0x8)
        c:/GitHub/errlog/regexp.go:41 +0x3e
github.com/snwfdhmp/errlog.(*logger).Debug(0xb5c130, 0x8cfe40, 0xc000106150, 0xc000081b20)
        c:/GitHub/errlog/logger.go:87 +0x7e
github.com/snwfdhmp/errlog.Debug(0x8cfe40, 0xc000106150, 0x3)
        c:/GitHub/errlog/errlog.go:89 +0x53
main.(*application).home(0xc000048dc0, 0x8d6640, 0xc00012e000, 0xc00011e000)
        c:/gitlab/learn-go/snippetbox/cmd/web/handlers.go:29 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc000048dd0, 0x8d6640, 0xc00012e000, 0xc00011e000)
        c:/go/src/net/http/server.go:2007 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc00001e4c0, 0x8d6640, 0xc00012e000, 0xc00011e000)
        c:/go/src/net/http/server.go:2387 +0x1c4
net/http.serverHandler.ServeHTTP(0xc0000e8000, 0x8d6640, 0xc00012e000, 0xc00011e000)
        c:/go/src/net/http/server.go:2802 +0xab
net/http.(*conn).serve(0xc000069720, 0x8d6d80, 0xc000108000)
        c:/go/src/net/http/server.go:1890 +0x87c
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2927 +0x395
```

Hope this helps.

Regards,

Jan

**Comment by jan-herout** [comment]
`$ go version`

```
go version go1.13.3 windows/amd64
```


`$ go env`

```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\janhe\AppData\Local\go-build
set GOENV=C:\Users\janhe\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\janhe\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=c:\gitlab\learn-go\snippetbox\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\janhe\AppData\Local\Temp\go-build594325738=/tmp/go-build -gno-record-gcc-switches
```

**Comment by snwfdhmp** [comment]
Hi @jan-herout,
Sorry I've a lot of work these days so I didn't see your issue. I'll check this asap.

**Comment by snwfdhmp** [comment]
Thanks for your report !

**Comment by Fonseca2570** [comment]
Any update on this same error here

**Comment by snwfdhmp** [comment]
@jan-herout @Fonseca2570 This should fix the issue with Windows paths, but I'm not sure of the result. The regexp is too big so I can't test it with appropriate tools. I need to change the way to parse the logs to improve both performance and compatibility.

Any help is welcome !

**Comment by snwfdhmp** [comment]
@jan-herout @Fonseca2570 if you guys have had any time to check, I'd be really happy to know

**Comment by Fonseca2570** [comment]
@snwfdhmp Made a quick test it shows the stack trace now, but it can't find the line where its coming from. When i have a little time i will look into it. I used the package to do something different i adapted it to only call the Debug once while it goes throw the logging system and print all the code erros. this way i didn't need to change the zap loggin system.

**Comment by snwfdhmp** [comment]
@Fonseca2570 thanks for your feedback. Any update on your side ?
